const app=document.getElementById('app');
const nav=[['home','⌂','Home'],['courses','▣','Courses'],['calendar','▦','Calendar'],['grades','▤','Grades'],['assignments','✓','Assignments'],['messages','✉','Messages'],['notifications','●','Notifications'],['people','♙','People'],['groups','♟','Groups'],['resources','▤','Resources'],['media','▶','Media'],['profile','●','Profile'],['settings','⚙','Account Settings']];
let state={page:'home',drawer:true,account:null,data:{},loading:false,error:null,toast:null};
const h=(s)=>s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
function toast(x){state.toast=x;render();setTimeout(()=>{state.toast=null;render()},2500)}
async function call(path,method='GET',body=null){state.loading=true;state.error=null;render();try{return await window.schoologyDesktop.api(path,method,body)}catch(e){state.error=e.message;throw e}finally{state.loading=false;render()}}
async function loadAccount(){state.account=await window.schoologyDesktop.account.get();render()}
function layout(content){return `<div class="top"><button class="hamb" onclick="toggleDrawer()">☰</button><div class="brand"><img src="../assets/schoology-logo.png"><span>Schoology</span></div><div class="top-right"><button class="topbtn" onclick="refreshPage()">↻</button><button class="topbtn" onclick="go('profile')">●</button></div></div><div class="layout"><aside class="drawer ${state.drawer?'':'closed'}">${nav.map(n=>`<div class="navitem ${state.page===n[0]?'active':''}" onclick="go('${n[0]}')"><span class="ico">${n[1]}</span><span>${n[2]}</span>${n[0]==='notifications'&&state.data.notifications?.length?'<span class="badge">'+state.data.notifications.length+'</span>':''}</div>`).join('')}<div class="navgroup"><div class="navtitle">Account</div><div class="navitem" onclick="logout()"><span class="ico">⇥</span><span>Log Out</span></div></div></aside><main class="main ${state.drawer?'':'full'}">${content}</main></div>${state.toast?`<div class="toast">${h(state.toast)}</div>`:''}`}
function page(title,sub,body){return `<div class="content"><div class="pagehead"><div><h1>${title}</h1>${sub?`<div class="sub">${sub}</div>`:''}</div></div>${state.error?`<div class="notice error">${h(state.error)} <button class="btn" onclick="state.error=null;render()">Dismiss</button></div>`:''}${body}</div>`}
function home(){return page('Home','Your Schoology dashboard',`<div class="grid"><div class="tile" onclick="go('courses')"><h3>Courses</h3><p>View your current courses and materials.</p></div><div class="tile" onclick="go('calendar')"><h3>Calendar</h3><p>Upcoming events, due dates and activities.</p></div><div class="tile" onclick="go('grades')"><h3>Grades</h3><p>Review grades and graded items.</p></div><div class="tile" onclick="go('assignments')"><h3>Assignments</h3><p>See work that needs attention.</p></div></div><div class="card"><div class="cardhead">Recent Activity</div><div class="cardbody">${state.data.activity?.length?state.data.activity.map(x=>`<div class="row"><div class="avatar">${(x.name||'S')[0]}</div><div class="grow"><b>${h(x.name||x.title||'Activity')}</b><div class="small">${h(x.description||x.timestamp||'')}</div></div></div>`).join(''):'<div class="empty">Sign in and refresh to load recent Schoology activity.</div>'}</div></div>`)}
function courses(){let d=state.data.courses;return page('Courses','Your Schoology courses',`<div class="card"><div class="cardhead">Courses <button class="btn" style="float:right" onclick="loadCourses()">Refresh</button></div><div class="cardbody">${d?.length?`<div class="grid">${d.map(c=>`<div class="tile" onclick="course(${c.id})"><h3>${h(c.course_title||c.title||'Course')}</h3><p>${h(c.course_code||c.section_title||'')}</p></div>`).join('')}</div>`:'<div class="empty">No courses loaded yet. Click Refresh.</div>'}</div></div>`)}
function calendar(){return page('Calendar','Upcoming Schoology events',`<div class="card"><div class="cardbody"><div class="calendar">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="calhead">${x}</div>`).join('')}${Array.from({length:35},(_,i)=>`<div class="calday"><b>${(i+1)<=31?(i+1):''}</b>${i===11?'<div class="event">Assignment due</div>':''}${i===18?'<div class="event">Course event</div>':''}</div>`).join('')}</div></div></div>`)}
function grades(){return page('Grades','Your grades and graded items',`<div class="card"><div class="cardhead">Grades</div><div class="cardbody">${state.data.grades?.length?`<table class="table"><thead><tr><th>Course</th><th>Item</th><th>Grade</th></tr></thead><tbody>${state.data.grades.map(g=>`<tr><td>${h(g.course_title||'')}</td><td>${h(g.title||g.assignment_title||'')}</td><td>${h(g.grade||g.score||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No grade data loaded yet.</div>'}</div></div>`)}
function listPage(title,key,endpoint,fields){let d=state.data[key];return page(title,'',`<div class="card"><div class="cardhead">${title} <button class="btn" style="float:right" onclick="loadList('${key}','${endpoint}')">Refresh</button></div><div class="cardbody">${d?.length?d.map(x=>`<div class="row"><div class="avatar">${((x.name||x.title||x.subject||title)[0]||'S').toUpperCase()}</div><div class="grow"><b>${h(x.name||x.title||x.subject||'')}</b><div class="small">${h(fields.map(f=>x[f]).filter(Boolean).join(' · '))}</div></div></div>`).join(''):'<div class="empty">No data loaded yet. Click Refresh.</div>'}</div></div>`)}
function profile(){return page('Profile','Your Schoology profile',`<div class="card"><div class="cardbody"><div class="row"><div class="avatar">${((state.data.me?.name||'S')[0])}</div><div class="grow"><h2>${h(state.data.me?.name||'Schoology User')}</h2><div class="sub">${h(state.data.me?.username||state.data.me?.email||'')}</div></div><button class="btn primary" onclick="loadMe()">Refresh</button></div></div></div>`)}
function settings(){return page('Account Settings','Schoology account and application settings',`<div class="card"><div class="cardhead">Application</div><div class="cardbody"><div class="row"><div class="grow"><b>Android compatibility mode</b><div class="small">Schoology Android v2025.04.0 identity is used for web/API requests.</div></div><span class="pill">Enabled</span></div><div class="row"><div class="grow"><b>Environment</b><div class="small">Live · api.schoology.com</div></div></div></div></div><div class="card"><div class="cardhead">Account</div><div class="cardbody"><button class="btn danger" onclick="logout()">Log Out</button></div></div>`)}
function login(){return `<div class="login"><div class="loginbox"><img class="loginlogo" src="../assets/schoology-logo.png"><h1>Sign in to Schoology</h1><div class="notice">This port uses the same OAuth-based Schoology authentication architecture recovered from the Android application.</div><button class="btn primary" style="width:100%;margin-top:10px" onclick="startLogin()">Continue with Schoology</button><div class="small" style="margin-top:18px">Your credentials are entered on Schoology's authorization page, not stored by this application.</div></div></div>`}
function render(){if(!state.account){app.innerHTML=login();return}const pages={home,courses,calendar,grades,assignments:()=>listPage('Assignments','assignments','users/me/assignments',['course_title','due','grade']),messages:()=>listPage('Messages','messages','messages',['subject','created']),notifications:()=>listPage('Notifications','notifications','notifications',['message','created']),people:()=>listPage('People','people','users',['username','role']),groups:()=>listPage('Groups','groups','groups',['description']),resources:()=>listPage('Resources','resources','resources',['description']),media:()=>listPage('Media','media','albums',['description']),profile,settings};const fn=pages[state.page]||home;app.innerHTML=layout(fn())}
async function startLogin(){try{const req=await window.schoologyDesktop.oauth.start();showVerifier(req)}catch(e){toast(e.message)}}
function showVerifier(req){const bg=document.createElement('div');bg.className='modalbg';bg.innerHTML=`<div class="modal"><h2>Schoology authorization</h2><p>A Schoology authorization page has opened in your browser. Complete sign-in there, then enter the verification code below.</p><input id="verifier" class="input" placeholder="Verification code"><div style="display:flex;gap:10px;margin-top:15px"><button class="btn" onclick="this.closest('.modalbg').remove()">Cancel</button><button class="btn primary" onclick="finishLogin(${JSON.stringify(req).replace(/</g,'\\u003c')},document.getElementById('verifier').value,this.closest('.modalbg'))">Finish sign in</button></div></div>`;document.body.appendChild(bg)}
async function finishLogin(req,v,el){if(!v)return;try{await window.schoologyDesktop.oauth.finish(req,v);el.remove();await loadAccount();await loadMe();}catch(e){alert(e.message)}}
async function loadMe(){try{state.data.me=await call('users/me');render()}catch{}}
async function loadCourses(){try{const d=await call('users/me/courses');state.data.courses=Array.isArray(d)?d:Object.values(d||{});render()}catch{}}
async function loadList(k,e){try{const d=await call(e);state.data[k]=Array.isArray(d)?d:Object.values(d||{});render()}catch{}}
async function course(id){try{const d=await call(`courses/${id}`);state.data.selectedCourse=d;toast(d.course_title||'Course loaded')}catch{}}
async function refreshPage(){if(state.page==='courses')return loadCourses();if(state.page==='profile')return loadMe();const map={assignments:['assignments','users/me/assignments'],messages:['messages','messages'],notifications:['notifications','notifications'],people:['people','users'],groups:['groups','groups'],resources:['resources','resources'],media:['media','albums']};if(map[state.page])return loadList(...map[state.page]);render()}
function go(p){state.page=p;state.error=null;render();if(p==='profile')loadMe();if(p==='courses')loadCourses()}
function toggleDrawer(){state.drawer=!state.drawer;render()} async function logout(){await window.schoologyDesktop.account.logout();state.account=null;render()}
Object.assign(window,{go,toggleDrawer,refreshPage,startLogin,finishLogin,loadCourses,loadList,loadMe,course,logout});loadAccount();
