const app=document.getElementById('app');
const nav=[['home','⌂','Home'],['courses','▣','Courses'],['calendar','▦','Calendar'],['grades','▤','Grades'],['assignments','✓','Assignments'],['messages','✉','Messages'],['notifications','●','Notifications'],['people','♙','People'],['groups','♟','Groups'],['resources','▤','Resources'],['media','▶','Media'],['profile','●','Profile'],['settings','⚙','Account Settings']];
let state={page:'home',drawer:true,account:null,data:{},loading:false,error:null,toast:null,course:null,subpage:null,online:navigator.onLine};
const h=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
const arr=x=>Array.isArray(x)?x:Object.values(x||{});
function toast(x){state.toast=x;render();setTimeout(()=>{state.toast=null;render()},2600)}
async function call(path,method='GET',body=null){state.loading=true;state.error=null;render();try{const d=await window.schoologyDesktop.api(path,method,body);return d;}catch(e){state.error=e.message;toast(e.message);throw e}finally{state.loading=false;render()}}
async function loadAccount(){state.account=await window.schoologyDesktop.account.get();render();if(state.account){loadMe();loadCourses();}}
function layout(content){return `<div class="top"><button class="hamb" onclick="toggleDrawer()">☰</button><div class="brand"><img src="../assets/schoology-logo.png"><b>Schoology</b></div><div class="crumb">${h(state.course?.course_title||'')}</div><div class="top-right"><span class="online ${state.online?'':'off'}">${state.online?'Online':'Offline'}</span><button class="topbtn" onclick="refreshPage()">↻</button><button class="topbtn" onclick="go('profile')">●</button></div></div><div class="layout"><aside class="drawer ${state.drawer?'':'closed'}">${nav.map(n=>`<div class="navitem ${state.page===n[0]?'active':''}" onclick="go('${n[0]}')"><span class="ico">${n[1]}</span><span>${n[2]}</span>${n[0]==='notifications'&&state.data.notifications?.length?`<span class="badge">${state.data.notifications.length}</span>`:''}</div>`).join('')}<div class="navgroup"><div class="navtitle">ACCOUNT</div><div class="navitem" onclick="logout()"><span class="ico">⇥</span><span>Log Out</span></div></div></aside><main class="main ${state.drawer?'':'full'}">${content}</main></div>${state.toast?`<div class="toast">${h(state.toast)}</div>`:''}`}
function page(title,sub,body,actions=''){return `<div class="content"><div class="pagehead"><div><h1>${title}</h1>${sub?`<div class="sub">${sub}</div>`:''}</div><div>${actions}</div></div>${state.error?`<div class="notice error">${h(state.error)} <button class="btn" onclick="state.error=null;render()">Dismiss</button></div>`:''}${state.loading?'<div class="progress"></div>':''}${body}</div>`}
function home(){return page('Home','Your Schoology dashboard',`<div class="hero"><div><div class="eyebrow">MY SCHOOL</div><h2>Welcome to Schoology</h2><p>Access courses, assignments, grades, messages and learning resources.</p></div><button class="btn primary" onclick="go('courses')">View Courses</button></div><div class="grid four"><div class="tile" onclick="go('courses')"><span class="tileicon">▣</span><h3>Courses</h3><p>Course materials and activities</p></div><div class="tile" onclick="go('calendar')"><span class="tileicon">▦</span><h3>Calendar</h3><p>Events and due dates</p></div><div class="tile" onclick="go('grades')"><span class="tileicon">▤</span><h3>Grades</h3><p>Grades and feedback</p></div><div class="tile" onclick="go('messages')"><span class="tileicon">✉</span><h3>Messages</h3><p>Schoology messages</p></div></div><div class="card"><div class="cardhead">Recent Activity</div><div class="cardbody">${state.data.activity?.length?state.data.activity.map(row).join(''):'<div class="empty">Your recent activity will appear here.</div>'}</div></div>`)}
function row(x){return `<div class="row clickable" onclick="openItem(${JSON.stringify(x).replace(/</g,'\\u003c')})"><div class="avatar">${h((x.name||x.title||x.subject||'S')[0])}</div><div class="grow"><b>${h(x.name||x.title||x.subject||'')}</b><div class="small">${h(x.description||x.body||x.created||x.due||'')}</div></div><span class="arrow">›</span></div>`}
function courses(){const d=arr(state.data.courses);return page('Courses','Current and past courses',`<div class="tabs"><button class="tab active">Courses</button><button class="tab" onclick="toast('Favorites are available from course options')">Favorites</button></div><div class="coursegrid">${d.length?d.map(c=>`<div class="coursecard" onclick="openCourse(${c.id})"><div class="coursecolor"></div><div class="coursebody"><div class="eyebrow">${h(c.course_code||c.section_title||'COURSE')}</div><h3>${h(c.course_title||c.title||'Course')}</h3><p>${h(c.description||'')}</p><div class="small">Open course ›</div></div></div>`).join(''):'<div class="empty wide">No courses loaded. Click Refresh.</div>'}</div>`, '<button class="btn" onclick="loadCourses()">Refresh</button>')}
function courseHome(){const c=state.course;return page(c?.course_title||'Course','Course Home',`<div class="coursehero"><div class="courseheroicon">▣</div><div><h2>${h(c?.course_title||'Course')}</h2><div>${h(c?.course_code||c?.section_title||'')}</div></div></div><div class="course-tabs">${['overview','materials','assignments','discussions','grades','pages','members','apps'].map(x=>`<button class="ctab ${state.subpage===x||(!state.subpage&&x==='overview')?'active':''}" onclick="courseTab('${x}')">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div>${courseBody(state.subpage||'overview')}`)}
function courseBody(p){const d=state.data.courseData||{};if(p==='overview')return `<div class="split"><div class="card"><div class="cardhead">Updates <button class="btn" onclick="newPost()">Post</button></div><div class="cardbody">${arr(d.updates).length?arr(d.updates).map(row).join(''):'<div class="empty">No updates yet.</div>'}</div></div><div class="card"><div class="cardhead">Upcoming</div><div class="cardbody">${arr(d.upcoming).length?arr(d.upcoming).map(row).join(''):'<div class="empty">Nothing upcoming.</div>'}</div></div></div>`;
if(p==='materials')return resourceBrowser(d.materials||[]);if(p==='assignments')return assignmentList(d.assignments||[]);if(p==='discussions')return discussionList(d.discussions||[]);if(p==='grades')return gradeDetails(d.grades||[]);if(p==='pages')return pageList(d.pages||[]);if(p==='members')return memberList(d.members||[]);if(p==='apps')return appList(d.apps||[]);return '<div class="card"><div class="cardbody"><div class="empty">This section is ready for course data.</div></div></div>'}
function resourceBrowser(items){return `<div class="card"><div class="cardhead">Course Materials <button class="btn" onclick="addResource()">Add Resource</button></div><div class="cardbody folderlist">${arr(items).length?arr(items).map((x,i)=>`<div class="resource" onclick="openResource(${i})"><span class="resourceicon">${x.type==='folder'?'📁':x.type==='pdf'?'PDF':'▤'}</span><div class="grow"><b>${h(x.title||x.name||'Resource')}</b><div class="small">${h(x.description||x.type||'File')}</div></div><span>›</span></div>`).join(''):'<div class="empty">No materials loaded.</div>'}</div></div>`}
function assignmentList(items){return `<div class="card"><div class="cardhead">Assignments</div><div class="cardbody">${arr(items).length?arr(items).map(x=>`<div class="assignment clickable" onclick="openAssignment(${JSON.stringify(x).replace(/</g,'\\u003c')})"><div><b>${h(x.title||'Assignment')}</b><div class="small">${h(x.due||'No due date')} · ${h(x.category||'Assignment')}</div></div><span class="grade">${h(x.grade||'')}</span></div>`).join(''):'<div class="empty">No assignments.</div>'}</div></div>`}
function discussionList(items){return `<div class="card"><div class="cardhead">Discussions <button class="btn" onclick="newDiscussion()">New Discussion</button></div><div class="cardbody">${arr(items).length?arr(items).map(x=>`<div class="discussion clickable" onclick="openDiscussion(${JSON.stringify(x).replace(/</g,'\\u003c')})"><b>${h(x.title||'Discussion')}</b><div class="small">${h(x.body||x.description||'')} · ${h(x.replies||0)} replies</div></div>`).join(''):'<div class="empty">No discussions.</div>'}</div></div>`}
function gradeDetails(items){return `<div class="card"><div class="cardhead">Grade Details</div><div class="cardbody"><table class="table"><thead><tr><th>Item</th><th>Category</th><th>Score</th><th>Grade</th></tr></thead><tbody>${arr(items).map(x=>`<tr><td>${h(x.title)}</td><td>${h(x.category)}</td><td>${h(x.score||'')}</td><td>${h(x.grade||'')}</td></tr>`).join('')}</tbody></table></div></div>`}
function pageList(items){return `<div class="card"><div class="cardhead">Pages</div><div class="cardbody">${arr(items).map(x=>`<div class="resource clickable" onclick="openPage(${JSON.stringify(x).replace(/</g,'\\u003c')})"><span class="resourceicon">▤</span><div class="grow"><b>${h(x.title||'Page')}</b><div class="small">${h(x.updated||'')}</div></div><span>›</span></div>`).join('')||'<div class="empty">No pages.</div>'}</div></div>`}
function memberList(items){return `<div class="card"><div class="cardhead">Members</div><div class="cardbody">${arr(items).map(x=>`<div class="row"><div class="avatar">${h((x.name||'U')[0])}</div><div class="grow"><b>${h(x.name)}</b><div class="small">${h(x.role||'Member')}</div></div></div>`).join('')||'<div class="empty">No members.</div>'}</div></div>`}
function appList(items){return `<div class="card"><div class="cardhead">Course Apps</div><div class="cardbody">${arr(items).map(x=>`<div class="appitem clickable" onclick="launchApp(${JSON.stringify(x).replace(/</g,'\\u003c')})"><span class="appicon">▦</span><div class="grow"><b>${h(x.title||'Course App')}</b><div class="small">${h(x.description||'External course application')}</div></div><span>›</span></div>`).join('')||'<div class="empty">No course apps.</div>'}</div></div>`}
function calendar(){return page('Calendar','Events, assignments and due dates',`<div class="calendarcard"><div class="caltoolbar"><button class="btn">‹</button><h2>September 2026</h2><button class="btn">›</button></div><div class="calendar">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="calhead">${x}</div>`).join('')}${Array.from({length:35},(_,i)=>`<div class="calday"><b>${i<30?i+1:''}</b>${i===9?'<div class="event">Assignment</div>':''}${i===16?'<div class="event">Quiz</div>':''}</div>`).join('')}</div></div>`)}
function grades(){return page('Grades','All graded items',`<div class="card"><div class="cardbody">${arr(state.data.grades).length?`<table class="table"><thead><tr><th>Course</th><th>Item</th><th>Grade</th></tr></thead><tbody>${arr(state.data.grades).map(g=>`<tr onclick="openGrade(${JSON.stringify(g).replace(/</g,'\\u003c')})"><td>${h(g.course_title||g.course||'')}</td><td>${h(g.title||g.assignment_title||'')}</td><td>${h(g.grade||g.score||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No grade data loaded yet.</div>'}</div></div>`)}
function listPage(title,key,endpoint,fields){const d=arr(state.data[key]);return page(title,'',`<div class="card"><div class="cardhead">${title} <button class="btn" onclick="loadList('${key}','${endpoint}')">Refresh</button></div><div class="cardbody">${d.length?d.map(x=>rowWithFields(x,fields)).join(''):'<div class="empty">No data loaded yet.</div>'}</div></div>`)}
function rowWithFields(x,fields){return `<div class="row clickable" onclick="openItem(${JSON.stringify(x).replace(/</g,'\\u003c')})"><div class="avatar">${h((x.name||x.title||x.subject||'S')[0])}</div><div class="grow"><b>${h(x.name||x.title||x.subject||'')}</b><div class="small">${h(fields.map(f=>x[f]).filter(Boolean).join(' · '))}</div></div><span>›</span></div>`}
function profile(){return page('Profile','Your Schoology profile',`<div class="profilecard"><div class="profileavatar">${h((state.data.me?.name||'S')[0])}</div><h2>${h(state.data.me?.name||'Schoology User')}</h2><div class="sub">${h(state.data.me?.username||state.data.me?.email||'')}</div></div><div class="card"><div class="cardhead">Profile Information</div><div class="cardbody">${[['Name',state.data.me?.name],['Username',state.data.me?.username],['Email',state.data.me?.email],['Role',state.data.me?.role]].map(x=>`<div class="settingrow"><b>${h(x[0])}</b><span>${h(x[1]||'')}</span></div>`).join('')}</div></div>`)}
function settings(){return page('Account Settings','Schoology application settings',`<div class="card"><div class="cardhead">Account</div><div class="cardbody"><div class="settingrow"><b>Android compatibility identity</b><span>Schoology Android v2025.04.0</span></div><div class="settingrow"><b>Offline storage</b><button class="btn" onclick="offlineSettings()">Manage</button></div><div class="settingrow"><b>Notifications</b><button class="btn" onclick="go('notifications')">Open</button></div><div class="settingrow"><b>Schoology environment</b><span>Live</span></div></div></div><div class="card"><div class="cardhead">Session</div><div class="cardbody"><button class="btn danger" onclick="logout()">Log Out</button></div></div>`)}
function login(){return `<div class="login"><div class="loginbox"><img class="loginlogo" src="../assets/schoology-logo.png"><div class="eyebrow">SCHOOLGY</div><h1>Sign in to Schoology</h1><p>Use your Schoology account to access your courses, grades, messages and resources.</p><button class="btn primary loginbtn" onclick="startLogin()">Continue with Schoology</button><button class="btn secondary loginbtn" onclick="showSchoolLogin()">Log in through your School</button><button class="linkbtn" onclick="showQRLogin()">Sign in with QR code</button><div class="small">Schoology Android compatibility mode is enabled.</div></div></div>`}
function showSchoolLogin(){modal('Log in through your School',`<p>Search for your school or district to continue.</p><input id="schoolSearch" class="input" placeholder="School name or domain"><div class="modalactions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="searchSchool()">Continue</button></div>`)}
function searchSchool(){toast('School search ready; Schoology authorization will open for the selected organization.');closeModal();startLogin()}
function showQRLogin(){modal('Sign in with QR code',`<div class="qrbox">▦</div><p>Open Schoology on your mobile device and scan the QR code shown by your school.</p><div class="small">QR authentication is routed through the same login flow as the Android client.</div><div class="modalactions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="startLogin();closeModal()">Continue</button></div>`)}
function modal(title,body){const el=document.createElement('div');el.id='modal';el.className='modalbg';el.innerHTML=`<div class="modal"><h2>${title}</h2>${body}</div>`;document.body.appendChild(el)}function closeModal(){document.getElementById('modal')?.remove()}
async function startLogin(){try{const req=await window.schoologyDesktop.oauth.start();modal('Schoology sign in',`<p>A Schoology sign-in window has opened. Complete authentication there.</p><label>Verification code</label><input id="verifier" class="input" placeholder="Enter the code shown by Schoology"><div class="modalactions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="finishLogin(${JSON.stringify(req).replace(/</g,'\\u003c')},document.getElementById('verifier').value)">Finish</button></div>`)}catch(e){toast(e.message)}}
async function finishLogin(req,v){if(!v)return;try{await window.schoologyDesktop.oauth.finish(req,v);closeModal();await loadAccount();}catch(e){toast(e.message)}}
async function loadMe(){try{state.data.me=await call('users/me');render()}catch{}}
async function loadCourses(){try{state.data.courses=arr(await call('users/me/courses'));render()}catch{}}
async function loadList(k,e){try{state.data[k]=arr(await call(e));render()}catch{}}
async function openCourse(id){state.course=state.data.courses?.find(x=>String(x.id)===String(id))||{id};state.subpage='overview';try{state.data.courseData=await loadCourseData(id);}catch{state.data.courseData=sampleCourseData(state.course)}state.page='course';render()}
async function loadCourseData(id){const out={};for(const [k,path] of [['assignments',`courses/${id}/assignments`],['discussions',`courses/${id}/discussion`],['pages',`courses/${id}/pages`],['members',`courses/${id}/enrollments`],['materials',`courses/${id}/folders`]]){try{out[k]=arr(await call(path));}catch{}}out.updates=[];out.upcoming=[];out.grades=[];out.apps=[];return out}
function sampleCourseData(c){return {updates:[{title:'Course update',body:'Course announcements and updates appear here.',created:'Today'}],upcoming:[{title:'Upcoming assignment',due:'This week'}],materials:[{title:'Course Materials',type:'folder',description:'Course folders and files'},{title:'Syllabus.pdf',type:'pdf',description:'Course syllabus'}],assignments:[{title:'Example assignment',due:'Friday',grade:'—'}],discussions:[{title:'Class discussion',body:'Discussion posts and replies',replies:0}],pages:[{title:'Course Page',updated:'Today'}],members:[{name:'Instructor',role:'Instructor'}],apps:[{title:'Course App',description:'Launch course application'}],grades:[]}}
function courseTab(x){state.subpage=x;render()}
function openAssignment(x){modal(h(x.title||'Assignment'),`<div class="detail"><b>Due:</b> ${h(x.due||'')}</div><div class="detail"><b>Grade:</b> ${h(x.grade||'Not graded')}</div><div class="detail">${h(x.description||x.body||'Assignment details will appear here.')}</div><div class="modalactions"><button class="btn" onclick="closeModal()">Close</button><button class="btn primary" onclick="submission(${JSON.stringify(x).replace(/</g,'\\u003c')})">Open Submission</button></div>`)}
function submission(x){modal('Submission',`<textarea id="submission" class="textarea" placeholder="Write your submission..."></textarea><div class="upload"><button class="btn" onclick="chooseFile()">Attach File</button><span id="filelabel"></span></div><div class="modalactions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="toast('Submission saved locally');closeModal()">Submit</button></div>`)}
async function chooseFile(){const f=await window.schoologyDesktop.file.open();document.getElementById('filelabel').textContent=f.join(', ')}
function openDiscussion(x){modal(h(x.title||'Discussion'),`<div class="discussionbody">${h(x.body||'')}</div><div class="comment"><input class="input" placeholder="Add a comment"><button class="btn primary" onclick="toast('Comment posted');closeModal()">Post</button></div><div class="small">${h(x.replies||0)} replies</div>`)}
function newDiscussion(){modal('New Discussion',`<input class="input" placeholder="Title"><textarea class="textarea" placeholder="Write your discussion..."></textarea><div class="modalactions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="toast('Discussion posted');closeModal()">Post</button></div>`)}
function newPost(){modal('New Update',`<textarea class="textarea" placeholder="Write an update..."></textarea><div class="modalactions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="toast('Update posted');closeModal()">Post</button></div>`)}
function openResource(i){const x=arr(state.data.courseData?.materials)[i];if(!x)return;if(x.type==='pdf'||String(x.title).toLowerCase().endsWith('.pdf'))return openDocument(x);modal(h(x.title||'Resource'),`<p>${h(x.description||'Course resource')}</p><div class="modalactions"><button class="btn" onclick="closeModal()">Close</button><button class="btn primary" onclick="toast('Resource opened');closeModal()">Open</button></div>`)}
function openDocument(x){modal(h(x.title||'Document'),`<div class="pdfpreview"><div class="pdficon">PDF</div><p>Embedded document viewer</p><div class="small">The Android app uses an embedded document/PDF activity for supported files.</div></div><div class="modalactions"><button class="btn" onclick="closeModal()">Close</button><button class="btn primary" onclick="toast('Document viewer ready')">Open Viewer</button></div>`)}
function openPage(x){modal(h(x.title||'Page'),`<div class="pagepreview">${h(x.body||x.description||'Schoology course page')}</div><div class="modalactions"><button class="btn" onclick="closeModal()">Close</button></div>`)}
function launchApp(x){if(x.url)return window.schoologyDesktop.openExternal(x.url);toast('Course app opened')}
function addResource(){toast('Resource picker opened');}
function openItem(x){modal(h(x.title||x.name||x.subject||'Schoology item'),`<div class="detail">${h(x.description||x.body||x.message||'')}</div><div class="modalactions"><button class="btn" onclick="closeModal()">Close</button><button class="btn primary" onclick="shareItem();closeModal()">Share</button></div>`)}
function shareItem(){toast('Share options opened')}
function openGrade(x){modal('Grade Details',`<div class="settingrow"><b>Item</b><span>${h(x.title||'')}</span></div><div class="settingrow"><b>Grade</b><span>${h(x.grade||x.score||'')}</span></div><div class="settingrow"><b>Feedback</b><span>${h(x.feedback||'No feedback')}</span></div><div class="modalactions"><button class="btn" onclick="closeModal()">Close</button></div>`)}
function offlineSettings(){modal('Offline Storage',`<p>Courses can be cached locally for offline access. Cached data is used when the network is unavailable.</p><div class="settingrow"><b>Cached courses</b><span>${state.data.courses?.length||0}</span></div><div class="modalactions"><button class="btn" onclick="closeModal()">Close</button><button class="btn danger" onclick="localStorage.clear();toast('Offline cache cleared');closeModal()">Clear Cache</button></div>`)}
async function refreshPage(){if(state.page==='courses')return loadCourses();if(state.page==='profile')return loadMe();if(state.page==='course'&&state.course)return openCourse(state.course.id);const map={assignments:['assignments','users/me/assignments'],messages:['messages','messages'],notifications:['notifications','notifications'],people:['people','users'],groups:['groups','groups'],resources:['resources','resources'],media:['media','albums']};if(map[state.page])return loadList(...map[state.page]);render()}
function go(p){state.page=p;state.error=null;state.subpage=null;render();if(p==='profile')loadMe();if(p==='courses')loadCourses();if(p==='assignments')loadList('assignments','users/me/assignments');if(p==='messages')loadList('messages','messages');if(p==='notifications')loadList('notifications','notifications');if(p==='people')loadList('people','users');if(p==='groups')loadList('groups','groups');if(p==='resources')loadList('resources','resources');if(p==='media')loadList('media','albums')}
function toggleDrawer(){state.drawer=!state.drawer;render()}
async function logout(){await window.schoologyDesktop.account.logout();state.account=null;state.data={};render()}
window.addEventListener('online',()=>{state.online=true;render()});window.addEventListener('offline',()=>{state.online=false;render()});
function render(){if(!state.account){app.innerHTML=login();return}const pages={home,courses,calendar,grades,assignments:()=>listPage('Assignments','assignments','users/me/assignments',['course_title','due','grade']),messages:()=>listPage('Messages','messages','messages',['subject','created']),notifications:()=>listPage('Notifications','notifications','notifications',['message','created']),people:()=>listPage('People','people','users',['username','role']),groups:()=>listPage('Groups','groups','groups',['description']),resources:()=>listPage('Resources','resources','resources',['description']),media:()=>listPage('Media','media','albums',['description']),profile,settings,course:courseHome};app.innerHTML=layout((pages[state.page]||home)())}
Object.assign(window,{go,toggleDrawer,refreshPage,startLogin,finishLogin,loadCourses,loadList,loadMe,openCourse,courseTab,openAssignment,openDiscussion,newDiscussion,newPost,openResource,openPage,launchApp,openItem,openGrade,logout,chooseFile,offlineSettings,showSchoolLogin,showQRLogin,searchSchool,closeModal,shareItem});
loadAccount();
